# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: rscohn2/oneapi-spec:latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install prerequisites
      run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive xargs -a ubuntu-packages.txt apt-get install -qq
          pip install --upgrade --quiet pip wheel
          pip install --upgrade --quiet -r requirements.txt
    - name: Builds and checks
      run: |
          pre-commit run --all
          mkdir -p build/reuse
          # ignore fail for reuse
          reuse lint > build/reuse/lint.txt || true
    - name: Archive build directory
      uses: actions/upload-artifact@v1
      with:
          name: build
          path: build
    - name: Checkout gh-pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
          cd gh-pages
          rm -rf *
          touch .nojekyll
          cp -r ../build/html/* .
          cp ../build/latex/*.pdf .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from github actions"
          git push
